name: Test preparation
on:
  workflow_dispatch:
    inputs:
      type:
        description: 'Type for deployment (hotfix, release, rollback)- in case of issues with the rollback please refer to manual process described here: https://github.com/MediaMarktSaturn/webmobile-deployment-manifest#rollback-deployment'
        required: true
        type: choice
        options:
          - hotfix
          - release
          - rollback
      deployment-region:
        description: 'Region'
        required: true
        type: choice
        options:
          - europe-west1
          - europe-west4
          - both
      app:
        description: 'app'
        required: true
        default: "test"
      branch:
        description: 'branch'
        required: true
        default: "test"
   
  push:
    branches:
      - 'test-mazen'
jobs:
  production-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout deployment action
        uses: actions/checkout@v4
        with:
          # This token is required to push changes back to the repository
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Run local action
        uses: ./.github/resources/
        with:
          app-name: ${{ github.event.inputs.app }}
          branch-name: ${{ github.event.inputs.branch }}
          deployment-region: ${{ github.event.inputs.deployment-region }} 
          production-deployment: true
          deployment-timeout: 600
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit report
        run: |
          git config --global user.name 'mazen423'
          git config --global user.email 'mazen423@users.noreply.github.com'
          git add -A
          git commit -am "Automated report"
          git push

